{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ff06301e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Divide by Zero: Write code that attempts to divide a number by zero. \n",
    "# What exception is raised in this case, and how can you handle it using a try-except block?\n",
    "\n",
    "#number = 7\n",
    "#print(number/0) ## ZeroDivisionError is raised and it can be handled as below:\n",
    "\n",
    "try:\n",
    "    number = int(input(\"Enter number\"))\n",
    "    if number < 0:\n",
    "        raise ValueError(\" Number must be greater than 0\") ## raising custom exception which needs to be catched by except\n",
    "    print(number/0)\n",
    "\n",
    "except ZeroDivisionError:\n",
    "    print(\"can't divide number by zero\")\n",
    "except ValueError as ve:\n",
    "    print(\"Error: \", ve)\n",
    "\n",
    "\n",
    "\n",
    "# Invalid Input: Create a program that takes user input for two numbers and performs division. \n",
    "# How can you handle the case where the user enters non-numeric input? \n",
    "# Implement error handling for this scenario.\n",
    "\n",
    "try:\n",
    "\n",
    "    number1 = int(input(\"Enter number1\"))\n",
    "    number2 = int(input(\"Enter number2\"))\n",
    "\n",
    "    print(number1/number2)\n",
    "\n",
    "except ValueError as e:\n",
    "    print(f'Error is {e}')\n",
    "\n",
    "\n",
    "# Missing Variable: Attempt to print the value of a variable that hasn't been defined. What exception does Python raise, and how can you handle it gracefully?\n",
    "try:\n",
    "    print(a)\n",
    "\n",
    "except NameError as E:\n",
    "    print(f'Error is {E}')\n",
    "\n",
    "# Index Error: Try to access an element of a list using an index that is out of range. \n",
    "# What is the name of the exception raised, and how can you catch it using a try-except block?\n",
    "try:\n",
    "    lst = [1,3,5,6,7]\n",
    "    i = 0\n",
    "    while i <= len(lst):\n",
    "        print(lst[i])\n",
    "        i+=1\n",
    "\n",
    "except IndexError as IE:\n",
    "    print(IE)\n",
    "\n",
    "# Type Error: Add a string and an integer together. What exception occurs, \n",
    "# and how can you handle type errors in Python?\n",
    "try:\n",
    "    string = \"Hello, GoodMorning\"\n",
    "    number = 7\n",
    "\n",
    "    print(string+number)\n",
    "\n",
    "except TypeError as TE:\n",
    "    print(TE)\n",
    "\n",
    "\n",
    "# File Not Found: Attempt to open a non-existent file using the open() function.  #study, do after file-handling\n",
    "# What exception is raised, and how can you handle file-related exceptions?\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "# Custom Exception: Define a custom exception class called CustomError \n",
    "# and raise it in your code. How can you create and raise custom exceptions in Python?\n",
    "\n",
    "class CustomError(NameError): ## the argument passed to the class CustomError must be inherited from the BaseException class\n",
    "    pass\n",
    "\n",
    "try:\n",
    "    text = input(\"Enter Fullname\")\n",
    "    if text != text.upper():\n",
    "        raise CustomError(\"Fullname must be in Capital Letters\")\n",
    "    print(text)\n",
    "except CustomError as CE: \n",
    "    print(\"CustomError is:\", CE)\n",
    "\n",
    "\n",
    "# Catch Multiple Exceptions: Modify your program to handle both \n",
    "# ZeroDivisionError and ValueError exceptions when performing division. \n",
    "# How can you catch multiple exceptions in a single try-except block?\n",
    "\n",
    "try:\n",
    "    n1 = int(input(\"Enter number1\"))\n",
    "    n2 = int(input(\"Enter number2\"))\n",
    "    print(n1/n2)\n",
    "except(ZeroDivisionError, ValueError) as e:\n",
    "    print(\"Error is:\",e)\n",
    "\n",
    "# Finally Block: Use a finally block in combination \n",
    "# with try and except to ensure that a piece of code is always executed, \n",
    "# regardless of whether an exception occurs or not. What is the purpose of the finally block?\n",
    "\n",
    "#ANS: Finally block will be executed no matter whichever error is raised and if isn't catched too.\n",
    "# In the below example ZeroDivisionError is raised and catched using except, after handling this the finally block is executed. In other scenario there is a chance of ValueError raising\n",
    "# which isn't handled below, even though the finally block is executed and the program has stopped abruptly\n",
    "try:\n",
    "    n1 = int(input(\"Enter number1\"))\n",
    "    n2 = int(input(\"Enter number2\"))\n",
    "    print(n1/n2)\n",
    "except(ZeroDivisionError) as e:\n",
    "    print(\"Error is:\",e)\n",
    "finally:\n",
    "    print(\"Need to start other program\")\n",
    "\n",
    "\n",
    "# Raising Exceptions: Write code that raises an exception with a \n",
    "# specific message using the raise keyword. \n",
    "# How can you raise exceptions with custom error messages in Python?\n",
    "\n",
    "try:\n",
    "    number = int(input(\"Enter number\"))\n",
    "    if number>100:\n",
    "        raise ValueError(\"Number must be between 0 and 100\")\n",
    "    \n",
    "except ValueError as E:\n",
    "    print(E)\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
